version: '2'

volumes:
  orderer.track-covid.org:
  peer0.companies.track-covid.org:
  peer0.ncdc.track-covid.org:
  peer0.test-centres.track-covid.org:

networks:
  track:

services:
  
  peer0.companies.track-covid.org:
    container_name: peer0.companies.track-covid.org
    extends:
      file: docker-base/docker-base-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.companies.track-covid.org
      - CORE_PEER_ADDRESS=peer0.companies.track-covid.org:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.companies.track-covid.org:7051
      - CORE_PEER_LOCALMSPID=companiesMSP
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.companies.track-covid.org:7053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7053
      - CORE_CHAINCODE_LOGGING_SHIM=INFO
    volumes:
      - ./crypto-config/peerOrganizations/companies.track-covid.org/peers/peer0.companies.track-covid.org/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/companies.track-covid.org/peers/peer0.companies.track-covid.org/tls:/etc/hyperledger/fabric/tls
      - peer0.companies.track-covid.org:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053
    networks:
      - track

  peer0.ncdc.track-covid.org:
    container_name: peer0.ncdc.track-covid.org
    extends:
      file: docker-base/docker-base-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.ncdc.track-covid.org
      - CORE_PEER_ADDRESS=peer0.ncdc.track-covid.org:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.ncdc.track-covid.org:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.ncdc.track-covid.org:9053
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9053
      - CORE_PEER_LOCALMSPID=ncdcMSP
      - CORE_CHAINCODE_LOGGING_SHIM=INFO
    volumes:
      - ./crypto-config/peerOrganizations/ncdc.track-covid.org/peers/peer0.ncdc.track-covid.org/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/ncdc.track-covid.org/peers/peer0.ncdc.track-covid.org/tls:/etc/hyperledger/fabric/tls
      - peer0.ncdc.track-covid.org:/var/hyperledger/production
    ports:
      - 9051:9051
      - 9053:9053
    networks:
      - track

  peer0.test-centres.track-covid.org:
    container_name: peer0.test-centres.track-covid.org
    extends:
      file: docker-base/docker-base-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.test-centres.track-covid.org
      - CORE_PEER_ADDRESS=peer0.test-centres.track-covid.org:11051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.test-centres.track-covid.org:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.test-centres.track-covid.org:11053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11053
      - CORE_PEER_LOCALMSPID=test-centresMSP
      - CORE_CHAINCODE_LOGGING_SHIM=INFO
    volumes:
      - ./crypto-config/peerOrganizations/test-centres.track-covid.org/peers/peer0.test-centres.track-covid.org/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/test-centres.track-covid.org/peers/peer0.test-centres.track-covid.org/tls:/etc/hyperledger/fabric/tls
      - peer0.test-centres.track-covid.org:/var/hyperledger/production
    ports:
      - 11051:11051
      - 11053:11053
    networks:
      - track

  orderer.track-covid.org:
    container_name: orderer.track-covid.org
    image: hyperledger/fabric-orderer:latest
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=file
      - ORDERER_GENERAL_BOOTSTRAPFILE=/var/hyperledger/orderer/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=ordererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=false
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/genesis.block
      - ./crypto-config/ordererOrganizations/ordrer.track-covid.org/orderers/orderer.ordrer.track-covid.org/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/ordrer.track-covid.org/orderers/orderer.ordrer.track-covid.org/tls:/var/hyperledger/orderer/tls
      - orderer.track-covid.org:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    networks:
      - track

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.companies.track-covid.org:7051
      - CORE_PEER_LOCALMSPID=companiesMSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/companies.track-covid.org/peers/peer0.companies.track-covid.org/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/companies.track-covid.org/users/Admin@companies.track-covid.org/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./../chaincode_adv:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
      - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
    depends_on:
      - orderer.track-covid.org
      - peer0.companies.track-covid.org
      - peer0.ncdc.track-covid.org
      - peer0.test-centres.track-covid.org
    networks:
      - track

  chaincode:
    container_name: chaincode
    image: hyperledger/fabric-nodeenv
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_ID=track
      - CORE_PEER_ADDRESS=peer0.companies.track-covid.org:7051
      - CORE_PEER_LOCALMSPID=companiesMSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/chaincode/crypto/peerOrganizations/companies.track-covid.org/users/Admin@companies.track-covid.org/msp
      - CORE_PEER_TLS_ENABLED=false
      # - CORE_CHAINCODE_ID_NAME="track:1.0"
    working_dir: /opt/gopath/src/chaincode
    command: /bin/sh -c 'sleep 6000000'
    volumes:
      - /var/run/:/host/var/run/
      - /crypto-config:/opt/gopath/src/chaincode/crypto/
      - ./../chaincode_adv:/opt/gopath/src/chaincode/
    networks:
      - track